### ISSUE TITLE
adjust app attributes

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/telegram-android#13]
Plz adjust attributes of app for uploading google store.
- app name, title
ref. to http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
■ target-branch= **poc2**

**Comment by nthtson** [comment]
com.proteusion.wrappy

**Comment by nthtson** [comment]
It will be change before publishing. This issue should be closed. Thanks.

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#13
