### ISSUE TITLE
review 20170302

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/telegram-android#5]
■ screens
1. screen [intro]
- image, button, text chưa hợp lý
- thêm screen chi tiết có tại đây (https://proteusion.atlassian.net/browse/PROTEUSION-16)

2. screen [Phone verification]
- font, text-color v.v. (tham khảo `Wrappy_mobile2-01.jpg`)

3. screen [Message, Info]
- layout, font, text v.v. (tham khảo `Wrappy_mobile2-06.jpg`)

4. screen [chats list]
- icon: cần thiết kế sắc sảo hơn (vị trí các icon trong vòng tròn chưa được cân bằng ?)
- chức năng đang được chọn thì icon có background màu trắng
- list-view có phân cách dash-line

5. screen [settings]
- icons, text v.v. Chú ý "Proteusion" (tham khảo `Wrappy_mobile2-03.jpg`)

■ source-code
- comment (file header) theo project hiện tại
- \TMessagesProj\src\main\AndroidManifest.xml
`org.telegram.ui.ProteustionSettingActivity`

■ pending
project-name, folder name, data folder, v.v.

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#5
